//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalonDbEntities : DbContext
    {
        public SalonDbEntities()
            : base("name=SalonDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblbarber> tblbarbers { get; set; }
        public virtual DbSet<tblcurrent_appointments> tblcurrent_appointments { get; set; }
        public virtual DbSet<tbllog> tbllogs { get; set; }
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblservice> tblservices { get; set; }
        public virtual DbSet<tblsalon> tblsalons { get; set; }
        public virtual DbSet<tblservice_booked> tblservice_booked { get; set; }
        public virtual DbSet<tblbarber_service> tblbarber_service { get; set; }
        public virtual DbSet<tblappointment> tblappointments { get; set; }
        public virtual DbSet<tblinvoice> tblinvoices { get; set; }
        public virtual DbSet<tblshop_owner> tblshop_owner { get; set; }
    }
}
