//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblappointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblappointment()
        {
            this.tblcurrent_appointments = new HashSet<tblcurrent_appointments>();
            this.tblservice_booked = new HashSet<tblservice_booked>();
            this.tblinvoices = new HashSet<tblinvoice>();
        }
    
        public int appointment_id { get; set; }
        public int appointment_no_for_day { get; set; }
        public int salon_id { get; set; }
        public System.DateTime due_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan expected_end_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public int barber_Id { get; set; }
        public int customer_id { get; set; }
        public bool canceled { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcurrent_appointments> tblcurrent_appointments { get; set; }
        public virtual tblbarber tblbarber { get; set; }
        public virtual tblcustomer tblcustomer { get; set; }
        public virtual tblsalon tblsalon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblservice_booked> tblservice_booked { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvoice> tblinvoices { get; set; }
    }
}
