//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbarber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblbarber()
        {
            this.tblcurrent_appointments = new HashSet<tblcurrent_appointments>();
            this.tblbarber_service = new HashSet<tblbarber_service>();
            this.tblappointments = new HashSet<tblappointment>();
        }
    
        public int barber_id { get; set; }
        public string barber_name { get; set; }
        public int salon_id { get; set; }
        public int allocated_seat_no { get; set; }
        public bool is_available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcurrent_appointments> tblcurrent_appointments { get; set; }
        public virtual tblsalon tblsalon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblbarber_service> tblbarber_service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblappointment> tblappointments { get; set; }
    }
}
