//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcurrent_appointments
    {
        public int current_appointment_id { get; set; }
        public int appointment_id { get; set; }
        public int salon_id { get; set; }
        public int barber_id { get; set; }
        public System.DateTime current_date { get; set; }
        public int last_appointment_no { get; set; }
    
        public virtual tblbarber tblbarber { get; set; }
        public virtual tblsalon tblsalon { get; set; }
        public virtual tblappointment tblappointment { get; set; }
    }
}
