//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice
    {
        public int invoice_id { get; set; }
        public int salon_id { get; set; }
        public int appointment_id { get; set; }
        public decimal total_price { get; set; }
        public decimal discount { get; set; }
        public decimal final_price { get; set; }
    
        public virtual tblappointment tblappointment { get; set; }
        public virtual tblsalon tblsalon { get; set; }
    }
}
