//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblshop_owner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblshop_owner()
        {
            this.tblsalons = new HashSet<tblsalon>();
        }
    
        public int owner_id { get; set; }
        public string name { get; set; }
        public int? contact_no { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string pin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblsalon> tblsalons { get; set; }
    }
}
